services:
  postgres:
    image: postgres:16-alpine3.22
    container_name: postgres-sftp
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres16-data:/var/lib/postgresql/data

  springboot:
    image: mirfanduri/sftp:v1.0.0
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres

volumes:
  postgres16-data:

# Setingan docker-compose diserver
#services:
#  postgres-sftp:
#    image: postgres:16-alpine3.22
#    container_name: postgres-sftp
#    ports:
#      - "5438:5432"
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    volumes:
#      - postgres16-data:/var/lib/postgresql/data
#
#  springboot-sftp:
#    image: mirfanduri/sftp:v1.0.0
#    ports:
#      - "8081:8081"
#    volumes:
#      - /home/nofrets.poai/pten/PTEN_OUT:/downloads
#    environment:
#      - POSTGRES_HOST=${POSTGRES_HOST}
#      - POSTGRES_PORT=${POSTGRES_PORT}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    depends_on:
#      - postgres-sftp
#
#volumes:
#  postgres16-data: