spring.application.name=demo-sftp

server.port=8081

### PostgreSQL
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5438}/sftp
spring.datasource.username=${POSTGRES_USER:myuser}
spring.datasource.password=${POSTGRES_PASSWORD:mypassword}

### sftp
pten.sftp.username=${PTEN_SFTP_USERNAME:prisma_link}
pten.sftp.host=${PTEN_SFTP_HOST:192.168.122.200}
pten.sftp.port=${PTEN_SFTP_PORT:22}
pten.sftp.password=${PTEN_SFTP_PASSWORD:1KXC5Mnn1q5U}

# SMTP server
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL:mirfan.duri@gmail.com}
spring.mail.password=${PASSWORD_EMAIL:password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC