spring.application.name=demo-sftp

server.port=8081

### PostgreSQL
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5438}/sftp
spring.datasource.username=${POSTGRES_USER:myuser}
spring.datasource.password=${POSTGRES_PASSWORD:mypassword}

### sftp
pten.sftp.username=${PTEN_SFTP_USERNAME:prisma_link}
pten.sftp.host=${PTEN_SFTP_HOST:192.168.122.200}
pten.sftp.port=${PTEN_SFTP_PORT:22}
pten.sftp.password=${PTEN_SFTP_PASSWORD:1KXC5Mnn1q5U}
